### PR TITLE
Email Validation

### PR DESCRIPTION
**Pull request by NoahZielke**
Is this what you guys had in mind as well? Or is there anything else that you can think to add?

PS - Very nice job on the email modal Corey, it looks really clean

https://user-images.githubusercontent.com/22875039/135487341-e2b197b8-e78e-40c4-80b2-56921ba18af1.mp4

@crmilsap @LoganElkins @hopsonp

### CODE REVIEW

**Comment by LoganElkins** [comment]
Yeah that works for me!

**Comment by hopsonp** [comment]
Looks good, I like it.

**Comment by NoahZielke** [comment]
Going to try to make button disabled when email is invalid per Corey's feedback

**Comment by NoahZielke** [comment]
Updated version, think it's good to go? @crmilsap

https://user-images.githubusercontent.com/22875039/135540037-c1136363-c5f1-4b37-86a5-bf35eabfd62e.mp4

**Comment by crmilsap** [comment]
Looks great! @NoahZielke

**Pull request merged**
